name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build project
        run: cargo build --release

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull latest code and deploy
        run: |
          cd /home/shard/dock/pricebot
          git pull origin master
          cargo build --release
          sudo systemctl --user restart discord-pricebot
